sudo: required
services:
  - docker

before_install:
  - docker build -t sanees2010 -f Dockerfile.dev .

script:
  - docker run -e CI=true sanees2010  npm run test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-430723739319"
  bucket_path: "docker"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
   secure: "$AWS_SECRET_KEY"
